import "@/styles/global.css";
import { FontStyle } from "@/lib/FontStyle";
import { BaseHeaderClient } from "@/components/shared/BaseHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <FontStyle />
      <body>
        <BaseHeaderClient />
        {children}
      </body>
    </html>
  );
}
